### ISSUE TITLE
Display options

### ISSUE THREAD

**Issue by nilshoerrmann** [TimOetting/kirby-color#1]
Thanks for this helpful plugin.

In order to handle different use cases, it would be nice if the field offered settings for the UI components shown in the color picker. I'm not sure how flexible the underlying Vue component is, but I'm thinking about something like this:

```yaml
color:
  label: Color
  type: color
  components: 
    - saturation: true
    - hue: false
    - input: false
    - presets: true
  presets:
    - "#fff"
```

This way, it would be possible to create a color picker with presets only or one that only offers the hex, rgb and hsa inputs.
