### ISSUE TITLE
Doesn't work when field is in a structure

### ISSUE THREAD

**Issue by bvdputte** [TimOetting/kirby-color#39]
This plugin doesn't work when the color field is used as field in a structure...

Error shown: `Cannot read properties of undefined (reading 'rgba')`.

Easy to replicate; add following in a structure:

```yaml
color:
  type: color
  editableAlpha: false
  label: Colour
```
